// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/article-listening/api/articles": {
            "get": {
                "description": "Article Listener for the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Article Listener",
                "operationId": "ArticleListenerHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseArticlesAll"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseArticlesAll"
                        }
                    }
                }
            }
        },
        "/article-listening/api/articles/:id": {
            "get": {
                "description": "Article Listener for the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Article Listener",
                "operationId": "ArticleListenerIdHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseArticle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseArticle"
                        }
                    }
                }
            }
        },
        "/article-listening/api/articles/slug/:slug": {
            "get": {
                "description": "Article Listener for the service",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "article"
                ],
                "summary": "Article Listener",
                "operationId": "ArticleListenerSlugHandler",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseArticle"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/model.ResponseArticle"
                        }
                    }
                }
            }
        },
        "/healthcheck": {
            "get": {
                "description": "Health checking for the service",
                "produces": [
                    "text/plain"
                ],
                "summary": "Health Check",
                "operationId": "HealthCheckHandler"
            }
        }
    },
    "definitions": {
        "model.Advisors": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "short_content": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "thumnail": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnail"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ArticlePayload": {
            "type": "object",
            "properties": {
                "advisors": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Advisors"
                    }
                },
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Categories"
                    }
                },
                "content": {
                    "type": "string"
                },
                "courses": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Courses"
                    }
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "thumnail": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnail"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "users_permissions_users": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.UsersPermissionsUsers"
                    }
                }
            }
        },
        "model.ArticlePayloads": {
            "type": "object",
            "properties": {
                "categories": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Categories"
                    }
                },
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ArticleThumnail": {
            "type": "object",
            "properties": {
                "alternativeText": {
                    "type": "string"
                },
                "caption": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "ext": {
                    "type": "string"
                },
                "formats": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnailDataAttributesFormat"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "previewUrl": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "provider_metadata": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                },
                "updatedAt": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.ArticleThumnailDataAttributesFormat": {
            "type": "object",
            "properties": {
                "large": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnailDataAttributesFormatLarge"
                },
                "medium": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnailDataAttributesFormatMedium"
                },
                "small": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnailDataAttributesFormatSmall"
                },
                "thumbnail": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnailDataAttributesFormatThumbnail"
                },
                "xsmall": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnailDataAttributesFormatXsmall"
                }
            }
        },
        "model.ArticleThumnailDataAttributesFormatLarge": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.ArticleThumnailDataAttributesFormatMedium": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.ArticleThumnailDataAttributesFormatSmall": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.ArticleThumnailDataAttributesFormatThumbnail": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.ArticleThumnailDataAttributesFormatXsmall": {
            "type": "object",
            "properties": {
                "ext": {
                    "type": "string"
                },
                "hash": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "mime": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "size": {
                    "type": "number"
                },
                "url": {
                    "type": "string"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "model.ArticlesPaginationContent": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "pageCount": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "model.Categories": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "publishedAt": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.Courses": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "locale": {
                    "type": "string"
                },
                "price": {
                    "type": "number"
                },
                "publishedAt": {
                    "type": "string"
                },
                "short_content": {
                    "type": "string"
                },
                "slug": {
                    "type": "string"
                },
                "thumnail": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticleThumnail"
                },
                "title": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "model.ResponseArticle": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "error"
                },
                "result": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticlePayload"
                }
            }
        },
        "model.ResponseArticlesAll": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "error"
                },
                "pagination": {
                    "type": "object",
                    "$ref": "#/definitions/model.ArticlesPaginationContent"
                },
                "result": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.ArticlePayloads"
                    }
                }
            }
        },
        "model.UsersPermissionsUsers": {
            "type": "object",
            "properties": {
                "agreement": {
                    "type": "boolean"
                },
                "blocked": {
                    "type": "boolean"
                },
                "confirmed": {
                    "type": "boolean"
                },
                "createdAt": {
                    "type": "string"
                },
                "dob": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "firstname": {
                    "type": "string"
                },
                "gender": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastname": {
                    "type": "string"
                },
                "middlename": {
                    "type": "string"
                },
                "provider": {
                    "type": "string"
                },
                "telephone": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "",
	Host:        "",
	BasePath:    "",
	Schemes:     []string{},
	Title:       "",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
